version: '3.1'

services:
  # psql -U db_user -h localhost -p 5432 lesson
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: db_user
      POSTGRES_DB: lesson
    ports:
        - '5432:5432'
    volumes:
        - .:/app
